name: perguntando
description: Learning project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  asp: ^1.3.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_crashlytics: ^3.3.5
  flutter_modular: ^6.0.4+1
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  result_dart: ^1.1.0
  sign_button: ^2.0.4
  uno: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0

flutter:
  uses-material-design: true
